# Generated by Django 4.1.5 on 2023-01-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librart_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creator_type',
            new_name='user_type',
        ),
    ]
