# Generated by Django 4.1.5 on 2023-01-11 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import librart_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('librart_main', '0002_alter_contentcreator_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=255, path='/images')),
                ('image_type', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), librart_main.models.max_value_current_year], verbose_name='year')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librart_main.collection')),
            ],
        ),
    ]
