# Generated by Django 4.1.5 on 2023-01-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librart_main', '0002_rename_creator_type_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
    ]
